// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {provider} from '../models';
import {context} from '../models';

export function GetCustomIgnoreRules():Promise<string>;

export function GetCustomPromptRules():Promise<string>;

export function GetLlmSettings():Promise<main.LLMSettings>;

export function HasActiveLlmKey():Promise<boolean>;

export function ListFiles(arg1:string):Promise<Array<main.FileNode>>;

export function ListLlmModels(arg1:string):Promise<Array<provider.ModelInfo>>;

export function RequestAutoContextSelection(arg1:string,arg2:Array<string>,arg3:string):Promise<Array<string>>;

export function RequestShotgunContextGeneration(arg1:string,arg2:Array<string>):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetCustomIgnoreRules(arg1:string):Promise<void>;

export function SetCustomPromptRules(arg1:string):Promise<void>;

export function SetLlmApiKey(arg1:string,arg2:string):Promise<void>;

export function SetLlmBaseURL(arg1:string):Promise<void>;

export function SetLlmModel(arg1:string,arg2:string):Promise<void>;

export function SetLlmProvider(arg1:string):Promise<void>;

export function SetUseCustomIgnore(arg1:boolean):Promise<void>;

export function SetUseGitignore(arg1:boolean):Promise<void>;

export function SplitShotgunDiff(arg1:string,arg2:number):Promise<Array<string>>;

export function StartFileWatcher(arg1:string):Promise<void>;

export function StartupTest(arg1:context.Context):Promise<void>;

export function StopFileWatcher():Promise<void>;
