// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCustomIgnoreRules() {
  return window['go']['main']['App']['GetCustomIgnoreRules']();
}

export function GetCustomPromptRules() {
  return window['go']['main']['App']['GetCustomPromptRules']();
}

export function GetLlmSettings() {
  return window['go']['main']['App']['GetLlmSettings']();
}

export function HasActiveLlmKey() {
  return window['go']['main']['App']['HasActiveLlmKey']();
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ListLlmModels(arg1) {
  return window['go']['main']['App']['ListLlmModels'](arg1);
}

export function RequestAutoContextSelection(arg1, arg2, arg3) {
  return window['go']['main']['App']['RequestAutoContextSelection'](arg1, arg2, arg3);
}

export function RequestShotgunContextGeneration(arg1, arg2) {
  return window['go']['main']['App']['RequestShotgunContextGeneration'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetCustomIgnoreRules(arg1) {
  return window['go']['main']['App']['SetCustomIgnoreRules'](arg1);
}

export function SetCustomPromptRules(arg1) {
  return window['go']['main']['App']['SetCustomPromptRules'](arg1);
}

export function SetLlmApiKey(arg1, arg2) {
  return window['go']['main']['App']['SetLlmApiKey'](arg1, arg2);
}

export function SetLlmBaseURL(arg1) {
  return window['go']['main']['App']['SetLlmBaseURL'](arg1);
}

export function SetLlmModel(arg1, arg2) {
  return window['go']['main']['App']['SetLlmModel'](arg1, arg2);
}

export function SetLlmProvider(arg1) {
  return window['go']['main']['App']['SetLlmProvider'](arg1);
}

export function SetUseCustomIgnore(arg1) {
  return window['go']['main']['App']['SetUseCustomIgnore'](arg1);
}

export function SetUseGitignore(arg1) {
  return window['go']['main']['App']['SetUseGitignore'](arg1);
}

export function SplitShotgunDiff(arg1, arg2) {
  return window['go']['main']['App']['SplitShotgunDiff'](arg1, arg2);
}

export function StartFileWatcher(arg1) {
  return window['go']['main']['App']['StartFileWatcher'](arg1);
}

export function StartupTest(arg1) {
  return window['go']['main']['App']['StartupTest'](arg1);
}

export function StopFileWatcher() {
  return window['go']['main']['App']['StopFileWatcher']();
}
