// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssembleFinalPrompt(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AssembleFinalPrompt'](arg1, arg2, arg3, arg4);
}

export function AuthorizeClaudeCli(arg1) {
  return window['go']['main']['App']['AuthorizeClaudeCli'](arg1);
}

export function AuthorizeCodexCli() {
  return window['go']['main']['App']['AuthorizeCodexCli']();
}

export function AuthorizeGeminiCli() {
  return window['go']['main']['App']['AuthorizeGeminiCli']();
}

export function CheckClaudeCli() {
  return window['go']['main']['App']['CheckClaudeCli']();
}

export function CheckCodexCli() {
  return window['go']['main']['App']['CheckCodexCli']();
}

export function CheckGeminiCli() {
  return window['go']['main']['App']['CheckGeminiCli']();
}

export function CommunicateWithGoogleAI(arg1) {
  return window['go']['main']['App']['CommunicateWithGoogleAI'](arg1);
}

export function ExecuteClaudeCli(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteClaudeCli'](arg1, arg2, arg3);
}

export function ExecuteCodexCli(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteCodexCli'](arg1, arg2, arg3);
}

export function ExecuteGeminiCli(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteGeminiCli'](arg1, arg2, arg3);
}

export function GetCustomIgnoreRules() {
  return window['go']['main']['App']['GetCustomIgnoreRules']();
}

export function GetCustomPromptRules() {
  return window['go']['main']['App']['GetCustomPromptRules']();
}

export function InstallCodexCli() {
  return window['go']['main']['App']['InstallCodexCli']();
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function LoadApiKey() {
  return window['go']['main']['App']['LoadApiKey']();
}

export function RequestShotgunContextGeneration(arg1, arg2) {
  return window['go']['main']['App']['RequestShotgunContextGeneration'](arg1, arg2);
}

export function SaveApiKey(arg1) {
  return window['go']['main']['App']['SaveApiKey'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetCustomIgnoreRules(arg1) {
  return window['go']['main']['App']['SetCustomIgnoreRules'](arg1);
}

export function SetCustomPromptRules(arg1) {
  return window['go']['main']['App']['SetCustomPromptRules'](arg1);
}

export function SetUseCustomIgnore(arg1) {
  return window['go']['main']['App']['SetUseCustomIgnore'](arg1);
}

export function SetUseGitignore(arg1) {
  return window['go']['main']['App']['SetUseGitignore'](arg1);
}

export function SplitShotgunDiff(arg1, arg2) {
  return window['go']['main']['App']['SplitShotgunDiff'](arg1, arg2);
}

export function StartFileWatcher(arg1) {
  return window['go']['main']['App']['StartFileWatcher'](arg1);
}

export function StartupTest(arg1) {
  return window['go']['main']['App']['StartupTest'](arg1);
}

export function StopFileWatcher() {
  return window['go']['main']['App']['StopFileWatcher']();
}
