// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AssembleFinalPrompt(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function CheckCursorInstallation():Promise<Record<string, string>>;

export function CommunicateWithGoogleAI(arg1:main.ChatRequest):Promise<void>;

export function ExecuteCliTool(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetCustomIgnoreRules():Promise<string>;

export function GetCustomPromptRules():Promise<string>;

export function InstallCursorCli():Promise<void>;

export function ListFiles(arg1:string):Promise<Array<main.FileNode>>;

export function LoadApiKey():Promise<string>;

export function RequestShotgunContextGeneration(arg1:string,arg2:Array<string>):Promise<void>;

export function SaveApiKey(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetCustomIgnoreRules(arg1:string):Promise<void>;

export function SetCustomPromptRules(arg1:string):Promise<void>;

export function SetUseCustomIgnore(arg1:boolean):Promise<void>;

export function SetUseGitignore(arg1:boolean):Promise<void>;

export function SplitShotgunDiff(arg1:string,arg2:number):Promise<Array<string>>;

export function StartFileWatcher(arg1:string):Promise<void>;

export function StartupTest(arg1:context.Context):Promise<void>;

export function StopFileWatcher():Promise<void>;

export function WSLClipboardSetText(arg1:string):Promise<void>;
